2022-02-03 15:47:25,780 INFO    MainThread:1199 [wandb_setup.py:_flush():71] setting env: {}
2022-02-03 15:47:25,780 INFO    MainThread:1199 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-03 15:47:25,780 INFO    MainThread:1199 [wandb_init.py:_log_setup():371] Logging user logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_154725-1mnvur0s/logs/debug.log
2022-02-03 15:47:25,781 INFO    MainThread:1199 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_154725-1mnvur0s/logs/debug-internal.log
2022-02-03 15:47:25,781 INFO    MainThread:1199 [wandb_init.py:init():404] calling init triggers
2022-02-03 15:47:25,781 INFO    MainThread:1199 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-03 15:47:25,781 INFO    MainThread:1199 [wandb_init.py:init():449] starting backend
2022-02-03 15:47:25,781 INFO    MainThread:1199 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-03 15:47:25,784 INFO    MainThread:1199 [backend.py:ensure_launched():199] starting backend process...
2022-02-03 15:47:25,788 INFO    MainThread:1199 [backend.py:ensure_launched():204] started backend process with pid: 1243
2022-02-03 15:47:25,791 INFO    MainThread:1199 [wandb_init.py:init():458] backend started and connected
2022-02-03 15:47:25,809 INFO    MainThread:1199 [wandb_run.py:_label_probe_notebook():917] probe notebook
2022-02-03 15:47:25,809 INFO    MainThread:1199 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-03 15:47:25,809 INFO    MainThread:1199 [wandb_init.py:init():519] updated telemetry
2022-02-03 15:47:25,831 INFO    MainThread:1199 [wandb_init.py:init():549] communicating current version
2022-02-03 15:47:30,833 INFO    MainThread:1199 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-03 15:48:00,838 INFO    MainThread:1199 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2022-02-03 15:48:00,839 ERROR   MainThread:1199 [wandb_init.py:init():569] backend process timed out
2022-02-03 15:48:00,839 ERROR   MainThread:1199 [wandb_init.py:init():578] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-03 15:48:12,839 INFO    MainThread:1199 [wandb_init.py:teardown():219] tearing down wandb.init
