
2022-04-01 23:29:09,891	INFO services.py:1412 -- View the Ray dashboard at [32m[1mhttp://127.0.0.1:8265
[36m(ServeController pid=32124)[39m 2022-04-01 23:29:14,310	INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
[36m(ServeController pid=32124)[39m 2022-04-01 23:29:14,418	INFO http_state.py:98 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:xJMqvK:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-04-01 23:29:14,654	INFO api.py:521 -- Started Serve instance in namespace 'serve'.
[36m(HTTPProxyActor pid=32119)[39m INFO:     Started server process [32119]
2022-04-01 23:29:14,679	INFO simple_q.py:154 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
2022-04-01 23:29:14,679	INFO trainer.py:779 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2022-04-01 23:29:14,739	WARNING util.py:55 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/loadmodel.py", line 40, in <module>
    trainer.restore(trained_model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/tune/trainable.py", line 490, in restore
    self.load_checkpoint(checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1861, in load_checkpoint
    self.__setstate__(extra_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 2509, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1333, in restore
    objs = pickle.loads(int.from_bytes(objs))
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/loadmodel.py", line 40, in <module>
    trainer.restore(trained_model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/tune/trainable.py", line 490, in restore
    self.load_checkpoint(checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1861, in load_checkpoint
    self.__setstate__(extra_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 2509, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1333, in restore
    objs = pickle.loads(int.from_bytes(objs))
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)