Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 69, in <module>
    wandb.config(allow_val=True)
TypeError: 'Config' object is not callable
Traceback (most recent call last):
  File "/Users/liwenyu/Documents/GitHub/RTDM/eva_ray_results.py", line 69, in <module>
    wandb.config(allow_val=True)
TypeError: 'Config' object is not callable